import React, { useState } from "react";
import axios from "axios";
import Head from "next/head";
import Header from "../components/Header";
import Layout from "../components/AboutLayouts";
import Footer from "../components/Footer";

export default function HireMe() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");

  const sendEmail = () => {
    const body = {
      name,
      email,
      message,
    };
    axios({
      method: "POST",
      url: "https://secret-savannah-26637.herokuapp.com/https://emeka-dev-email-service.herokuapp.com/send",
      data: body,
    }).then((response) => {
      if (response.data.status === "success") {
        console.log("Message successful to send.");
      } else if (response.data.status === "fail") {
       console.log("Message failed to send.");
      }
    }).catch((err) => {
        console.log(err)
    });
  };

  return (
    <>
      <Head>
        <title>Contact me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="w-full p-8">
        <section className="bg-white ">
          <div className="mx-auto max-w-screen-md py-8 px-4 lg:py-16">
            <h2 className="mb-4 text-center text-4xl font-extrabold tracking-tight text-gray-900 ">
              Contact Me
            </h2>
            <p className="mb-8 text-center font-light text-gray-500 sm:text-xl  lg:mb-16">
              Got a technical issue? Want to send feedback about a beta feature?
              Need help about a project? Let me know.
            </p>
            <div className="space-y-6">
        
              <div>
                <label
                  htmlFor="email"
                  className="mb-2 block text-sm font-medium text-gray-900"
                >
                  Your email
                </label>
                <input
                  type="email"
                  id="email"
                  onChange={(e) => setEmail(e.target.value) }
                  className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500"
                  placeholder="name@flowbite.com"
                  required
                />
              </div>
              <div>
                <label
                  htmlFor="subject"
                  className="mb-2 block text-sm font-medium text-gray-900"
                >
                  Subject
                </label>
                <input
                  type="text"
                  id="subject"
                  onChange={(e) => setName(e.target.value)}
                  className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-3 text-sm text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500"
                  placeholder="John doe"
                  required
                />
              </div>

              <div className="sm:col-span-2">
                <label
                  htmlFor="message"
                  className="mb-2 block text-sm font-medium text-gray-900 "
                >
                  Your message
                </label>
                <textarea
                  id="message"
                  rows="6"
                  onChange={(e) => setMessage(e.target.value)}
                  className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 "
                  placeholder="Leave a comment..."
                ></textarea>
              </div>
              <a className="rounded-lg block bg-blue-700 py-3 px-5 text-center text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 sm:w-fit"
               href={`mailto:aguchukwuemekag@gmail.com?subject=${name}&body=${message}`}>Send message</a>
              
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
