import Head from "next/head";
import Header from "../components/Header";
import Layout from "../components/AboutLayouts";
import Footer from "../components/Footer";

export default function HireMe() {
    return (
        <>
            <Head>
                <title>About me</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

        </>
    );
}
