import Head from "next/head";
import Header from "../components/Header";
import Layout from "../components/ProjectLayouts";
import Footer from "../components/Footer";

export default function Projects() {
    return (
        <>
            <Head>
                <title>Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Layout />
            {/* <Footer /> */}
        </>
    );
}
